/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;


import controller.CadastroDAO;
import model.Usuario;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author iriam
 */
public class CadastroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuario
     */
    public CadastroView() {
        initComponents();
    }

    public JButton getBtnCadastro() {
        return btnCadastro;
    }

    public void setBtnCadastro(JButton btnCadastro) {
        this.btnCadastro = btnCadastro;
    }

    public JTextField getCpfCad() {
        return cpfCad;
    }

    public void setCpfCad(JTextField cpfCad) {
        this.cpfCad = cpfCad;
    }

    public JTextField getEmailCad() {
        return emailCad;
    }

    public void setEmailCad(JTextField emailCad) {
        this.emailCad = emailCad;
    }

    public JTextField getEmpresaCad() {
        return empresaCad;
    }

    public void setEmpresaCad(JTextField empresaCad) {
        this.empresaCad = empresaCad;
    }

    public JTextField getIdFuncCad() {
        return idFuncCad;
    }

    public void setIdFuncCad(JTextField idFuncCad) {
        this.idFuncCad = idFuncCad;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getNomeCad() {
        return nomeCad;
    }

    public void setNomeCad(JTextField nomeCad) {
        this.nomeCad = nomeCad;
    }

    public JPasswordField getSenhaCad() {
        return senhaCad;
    }

    public void setSenhaCad(JPasswordField senhaCad) {
        this.senhaCad = senhaCad;
    }

    public JTextField getSobrenomeCad() {
        return sobrenomeCad;
    }

    public void setSobrenomeCad(JTextField sobrenomeCad) {
        this.sobrenomeCad = sobrenomeCad;
    }

    public JTextField getTelefoneCad() {
        return telefoneCad;
    }

    public void setTelefoneCad(JTextField telefoneCad) {
        this.telefoneCad = telefoneCad;
    }

    static Scanner scan = new Scanner(System.in);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeCad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        empresaCad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailCad = new javax.swing.JTextField();
        idFuncCad = new javax.swing.JTextField();
        cpfCad = new javax.swing.JTextField();
        telefoneCad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        senhaCad = new javax.swing.JPasswordField();
        btnCadastro = new javax.swing.JButton();
        sobrenomeCad = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);

        nomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadActionPerformed(evt);
            }
        });

        jLabel1.setText("Email:");

        jLabel9.setText("Sobrenome:");

        jLabel2.setText("CPF:");

        jLabel10.setText("Nome:");

        jLabel3.setText("id Empresa:");

        jLabel11.setText("Telefone:");

        jLabel4.setText("id Func:");

        emailCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCadActionPerformed(evt);
            }
        });

        cpfCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCadActionPerformed(evt);
            }
        });

        telefoneCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneCadActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha:");

        senhaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCadActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        sobrenomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cpfCad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailCad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaCad)
                    .addComponent(sobrenomeCad)
                    .addComponent(nomeCad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empresaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idFuncCad, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneCad, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(empresaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idFuncCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnCadastro)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadActionPerformed

    private void emailCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCadActionPerformed

    private void cpfCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCadActionPerformed

    private void telefoneCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneCadActionPerformed

    private void senhaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCadActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:

        String nomePessoa = nomeCad.getText();
        String sobrenomePessoa = sobrenomeCad.getText();
        String emailPessoa = emailCad.getText();
        String cpfPessoa = cpfCad.getText();
        String telefonePessoa = telefoneCad.getText();
        int idEmpresa = Integer.parseInt(empresaCad.getText());
        int idFunc = Integer.parseInt(idFuncCad.getText());
        String senhaPessoa = senhaCad.getText();

        Usuario cadastro = new Usuario();
        cadastro.setNome(nomePessoa);
        cadastro.setSobrenome(sobrenomePessoa);
        cadastro.setEmail(emailPessoa);
        cadastro.setCpf(cpfPessoa);
        cadastro.setTelefone(telefonePessoa);
        cadastro.setIdEmpresa(idEmpresa);
        cadastro.setIdFunc(idFunc);
        cadastro.setSenha(senhaPessoa);

        System.out.println("nome: " + nomePessoa);
        System.out.println("sobrenome: " + sobrenomePessoa);
        System.out.println("email: " + emailPessoa);
        System.out.println("cpf: " + cpfPessoa);
        System.out.println("senha: " + senhaPessoa);
        System.out.println("id empresa: " + idEmpresa);
        System.out.println("id funcionario: " + idFunc);
        System.out.println("telefone: " + telefonePessoa);

        CadastroDAO cadastroDAO = new CadastroDAO();
        cadastroDAO.cadastrar(cadastro);

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void sobrenomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeCadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JTextField cpfCad;
    private javax.swing.JTextField emailCad;
    private javax.swing.JTextField empresaCad;
    private javax.swing.JTextField idFuncCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCad;
    private javax.swing.JPasswordField senhaCad;
    private javax.swing.JTextField sobrenomeCad;
    private javax.swing.JTextField telefoneCad;
    // End of variables declaration//GEN-END:variables
}
