/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import DAO.VeiculoDAO;
import model.Veiculo;
import DAO.CadastroDAO;
import beans.Usuario;

/**
 *
 * @author iriam
 */
public class NovoVeiculo extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form NovoVeiculo
     */
    public NovoVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idVeic = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        marcaVeic = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        modeloVeic = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        btnRegVeic = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        combustivelVeic = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        autonomia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idEmp = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);

        jLabel1.setText("Id do veículo:");

        jScrollPane1.setViewportView(idVeic);

        jLabel2.setText("Marca:");

        jScrollPane2.setViewportView(marcaVeic);

        jLabel3.setText("Modelo:");

        jScrollPane3.setViewportView(modeloVeic);

        jLabel4.setText("Combustível:");

        btnRegVeic.setText("Registrar Veículo");
        btnRegVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVeicActionPerformed(evt);
            }
        });

        combustivelVeic.setBorder(null);
        combustivelVeic.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gasolina", "Etanol", "Diesel", "Gás natural" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(combustivelVeic);

        jLabel5.setText("Autonomia:");

        autonomia.setText("km/L (apenas números)");
        autonomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autonomiaActionPerformed(evt);
            }
        });

        jLabel6.setText("id Empresa:");

        idEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(autonomia)
                            .addComponent(idEmp))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(autonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addComponent(btnRegVeic)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVeicActionPerformed
        // TODO add your handling code here:
      
        int idVeiculo = Integer.parseInt(idVeic.getText());
        String marcaVeiculo = marcaVeic.getText();
        String modeloVeiculo = modeloVeic.getText();
        String idComb = combustivelVeic.getSelectedValue();
        int veicOnomia = Integer.parseInt(autonomia.getText());
        int idEmpresa = Integer.parseInt(idEmp.getText());
        
        Veiculo veiculo = new Veiculo();
        veiculo.setIdVeic(idVeiculo);
        veiculo.setMarca(marcaVeiculo);
        veiculo.setModelo(modeloVeiculo);
        veiculo.setIdComb(idComb);
        veiculo.setAutonomia(veicOnomia);
        veiculo.setIdEmpresa(idEmpresa);
        
        
        System.out.println("id do veiculo: " + idVeiculo);
        System.out.println("marca: " + marcaVeiculo);
        System.out.println("modelo: " + modeloVeiculo);
        System.out.println("combustivel: " + idComb);
        System.out.println("autonomia: " + veicOnomia);
        System.out.println("id da empresa responsável:" + idEmpresa);
        
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        veiculoDAO.cadastrarVeiculo(veiculo);
    }//GEN-LAST:event_btnRegVeicActionPerformed

    private void autonomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autonomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autonomiaActionPerformed

    private void idEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autonomia;
    private javax.swing.JButton btnRegVeic;
    private javax.swing.JList<String> combustivelVeic;
    private javax.swing.JTextField idEmp;
    private javax.swing.JTextPane idVeic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane marcaVeic;
    private javax.swing.JTextPane modeloVeic;
    // End of variables declaration//GEN-END:variables
}
